# version: "3.8"

services:
  db:
    env_file:
      - .env
    image: postgres:alpine
    build: .
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-db:/var/lib/postgressql/data

volumes:
  postgres-db:
